# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\environment\eric_workspace\6068pc_controller\main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(837, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.readyData = QtWidgets.QLineEdit(self.centralWidget)
        self.readyData.setGeometry(QtCore.QRect(30, 50, 113, 20))
        self.readyData.setObjectName("readyData")
        self.dataSend = QtWidgets.QPushButton(self.centralWidget)
        self.dataSend.setGeometry(QtCore.QRect(160, 50, 75, 23))
        self.dataSend.setObjectName("dataSend")
        self.systemTime = QtWidgets.QLabel(self.centralWidget)
        self.systemTime.setGeometry(QtCore.QRect(260, 10, 71, 21))
        self.systemTime.setObjectName("systemTime")
        self.systemTimeShow = QtWidgets.QLabel(self.centralWidget)
        self.systemTimeShow.setGeometry(QtCore.QRect(360, 10, 71, 21))
        self.systemTimeShow.setObjectName("systemTimeShow")
        self.timerInterval = QtWidgets.QLabel(self.centralWidget)
        self.timerInterval.setGeometry(QtCore.QRect(30, 110, 71, 21))
        self.timerInterval.setObjectName("timerInterval")
        self.timerUnit = QtWidgets.QLabel(self.centralWidget)
        self.timerUnit.setGeometry(QtCore.QRect(160, 110, 71, 21))
        self.timerUnit.setObjectName("timerUnit")
        self.runTime = QtWidgets.QLabel(self.centralWidget)
        self.runTime.setGeometry(QtCore.QRect(30, 150, 71, 21))
        self.runTime.setObjectName("runTime")
        self.protocolData = QtWidgets.QPushButton(self.centralWidget)
        self.protocolData.setGeometry(QtCore.QRect(650, 40, 75, 23))
        self.protocolData.setObjectName("protocolData")
        self.readCanData = QtWidgets.QPushButton(self.centralWidget)
        self.readCanData.setGeometry(QtCore.QRect(650, 80, 75, 23))
        self.readCanData.setObjectName("readCanData")
        self.canDataTable = QtWidgets.QTableView(self.centralWidget)
        self.canDataTable.setGeometry(QtCore.QRect(510, 120, 256, 192))
        self.canDataTable.setObjectName("canDataTable")
        self.setOrReset = QtWidgets.QPushButton(self.centralWidget)
        self.setOrReset.setGeometry(QtCore.QRect(630, 490, 75, 23))
        self.setOrReset.setObjectName("setOrReset")
        self.rebot = QtWidgets.QPushButton(self.centralWidget)
        self.rebot.setGeometry(QtCore.QRect(50, 480, 75, 23))
        self.rebot.setObjectName("rebot")
        self.shutDown = QtWidgets.QPushButton(self.centralWidget)
        self.shutDown.setGeometry(QtCore.QRect(10, 510, 75, 23))
        self.shutDown.setObjectName("shutDown")
        self.other = QtWidgets.QPushButton(self.centralWidget)
        self.other.setGeometry(QtCore.QRect(110, 530, 75, 23))
        self.other.setObjectName("other")
        self.timerIntervalShow = QtWidgets.QLabel(self.centralWidget)
        self.timerIntervalShow.setGeometry(QtCore.QRect(100, 110, 54, 12))
        self.timerIntervalShow.setObjectName("timerIntervalShow")
        self.runTimeShow = QtWidgets.QLabel(self.centralWidget)
        self.runTimeShow.setGeometry(QtCore.QRect(100, 160, 54, 12))
        self.runTimeShow.setObjectName("runTimeShow")
        self.dataTimerSend = QtWidgets.QPushButton(self.centralWidget)
        self.dataTimerSend.setGeometry(QtCore.QRect(160, 80, 75, 23))
        self.dataTimerSend.setObjectName("dataTimerSend")
        self.readyTimerData = QtWidgets.QLineEdit(self.centralWidget)
        self.readyTimerData.setGeometry(QtCore.QRect(30, 80, 113, 20))
        self.readyTimerData.setObjectName("readyTimerData")
        self.stopTimer = QtWidgets.QPushButton(self.centralWidget)
        self.stopTimer.setGeometry(QtCore.QRect(160, 150, 75, 23))
        self.stopTimer.setObjectName("stopTimer")
        self.list = QtWidgets.QLabel(self.centralWidget)
        self.list.setGeometry(QtCore.QRect(30, 220, 21, 21))
        self.list.setObjectName("list")
        self.secondSend = QtWidgets.QLabel(self.centralWidget)
        self.secondSend.setGeometry(QtCore.QRect(90, 220, 21, 21))
        self.secondSend.setObjectName("secondSend")
        self.time1 = QtWidgets.QLineEdit(self.centralWidget)
        self.time1.setGeometry(QtCore.QRect(50, 220, 31, 20))
        self.time1.setObjectName("time1")
        self.data1 = QtWidgets.QLineEdit(self.centralWidget)
        self.data1.setGeometry(QtCore.QRect(120, 220, 31, 20))
        self.data1.setObjectName("data1")
        self.data1_2 = QtWidgets.QLineEdit(self.centralWidget)
        self.data1_2.setGeometry(QtCore.QRect(120, 250, 31, 20))
        self.data1_2.setObjectName("data1_2")
        self.list_2 = QtWidgets.QLabel(self.centralWidget)
        self.list_2.setGeometry(QtCore.QRect(30, 250, 21, 21))
        self.list_2.setObjectName("list_2")
        self.time1_2 = QtWidgets.QLineEdit(self.centralWidget)
        self.time1_2.setGeometry(QtCore.QRect(50, 250, 31, 20))
        self.time1_2.setObjectName("time1_2")
        self.secondSend_2 = QtWidgets.QLabel(self.centralWidget)
        self.secondSend_2.setGeometry(QtCore.QRect(90, 250, 21, 21))
        self.secondSend_2.setObjectName("secondSend_2")
        self.data1_3 = QtWidgets.QLineEdit(self.centralWidget)
        self.data1_3.setGeometry(QtCore.QRect(120, 280, 31, 20))
        self.data1_3.setObjectName("data1_3")
        self.list_3 = QtWidgets.QLabel(self.centralWidget)
        self.list_3.setGeometry(QtCore.QRect(30, 280, 21, 21))
        self.list_3.setObjectName("list_3")
        self.time1_3 = QtWidgets.QLineEdit(self.centralWidget)
        self.time1_3.setGeometry(QtCore.QRect(50, 280, 31, 20))
        self.time1_3.setObjectName("time1_3")
        self.secondSend_3 = QtWidgets.QLabel(self.centralWidget)
        self.secondSend_3.setGeometry(QtCore.QRect(90, 280, 21, 21))
        self.secondSend_3.setObjectName("secondSend_3")
        self.data1_4 = QtWidgets.QLineEdit(self.centralWidget)
        self.data1_4.setGeometry(QtCore.QRect(120, 310, 31, 20))
        self.data1_4.setObjectName("data1_4")
        self.list_4 = QtWidgets.QLabel(self.centralWidget)
        self.list_4.setGeometry(QtCore.QRect(30, 310, 21, 21))
        self.list_4.setObjectName("list_4")
        self.time1_4 = QtWidgets.QLineEdit(self.centralWidget)
        self.time1_4.setGeometry(QtCore.QRect(50, 310, 31, 20))
        self.time1_4.setObjectName("time1_4")
        self.secondSend_4 = QtWidgets.QLabel(self.centralWidget)
        self.secondSend_4.setGeometry(QtCore.QRect(90, 310, 21, 21))
        self.secondSend_4.setObjectName("secondSend_4")
        self.data1_5 = QtWidgets.QLineEdit(self.centralWidget)
        self.data1_5.setGeometry(QtCore.QRect(120, 340, 31, 20))
        self.data1_5.setObjectName("data1_5")
        self.list_5 = QtWidgets.QLabel(self.centralWidget)
        self.list_5.setGeometry(QtCore.QRect(30, 340, 21, 21))
        self.list_5.setObjectName("list_5")
        self.time1_5 = QtWidgets.QLineEdit(self.centralWidget)
        self.time1_5.setGeometry(QtCore.QRect(50, 340, 31, 20))
        self.time1_5.setObjectName("time1_5")
        self.secondSend_5 = QtWidgets.QLabel(self.centralWidget)
        self.secondSend_5.setGeometry(QtCore.QRect(90, 340, 21, 21))
        self.secondSend_5.setObjectName("secondSend_5")
        self.dataSend_list = QtWidgets.QPushButton(self.centralWidget)
        self.dataSend_list.setGeometry(QtCore.QRect(60, 370, 75, 23))
        self.dataSend_list.setObjectName("dataSend_list")
        self.ipAddress = QtWidgets.QLineEdit(self.centralWidget)
        self.ipAddress.setGeometry(QtCore.QRect(270, 50, 113, 20))
        self.ipAddress.setObjectName("ipAddress")
        self.connectPort = QtWidgets.QLineEdit(self.centralWidget)
        self.connectPort.setGeometry(QtCore.QRect(270, 80, 113, 20))
        self.connectPort.setObjectName("connectPort")
        self.startConnect = QtWidgets.QPushButton(self.centralWidget)
        self.startConnect.setGeometry(QtCore.QRect(290, 110, 75, 23))
        self.startConnect.setObjectName("startConnect")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dataSend.setText(_translate("MainWindow", "单次发"))
        self.systemTime.setText(_translate("MainWindow", "系统时间"))
        self.systemTimeShow.setText(_translate("MainWindow", "2018.9.22"))
        self.timerInterval.setText(_translate("MainWindow", "定时器间隔"))
        self.timerUnit.setText(_translate("MainWindow", "s"))
        self.runTime.setText(_translate("MainWindow", "已走时"))
        self.protocolData.setText(_translate("MainWindow", "查看协议表"))
        self.readCanData.setText(_translate("MainWindow", "读取Can数据"))
        self.setOrReset.setText(_translate("MainWindow", "设置"))
        self.rebot.setText(_translate("MainWindow", "重启"))
        self.shutDown.setText(_translate("MainWindow", "关机"))
        self.other.setText(_translate("MainWindow", "其它"))
        self.timerIntervalShow.setText(_translate("MainWindow", "1"))
        self.runTimeShow.setText(_translate("MainWindow", "0"))
        self.dataTimerSend.setText(_translate("MainWindow", "定时发"))
        self.stopTimer.setText(_translate("MainWindow", "停止发送"))
        self.list.setText(_translate("MainWindow", "第"))
        self.secondSend.setText(_translate("MainWindow", "秒发送"))
        self.list_2.setText(_translate("MainWindow", "第"))
        self.secondSend_2.setText(_translate("MainWindow", "秒发送"))
        self.list_3.setText(_translate("MainWindow", "第"))
        self.secondSend_3.setText(_translate("MainWindow", "秒发送"))
        self.list_4.setText(_translate("MainWindow", "第"))
        self.secondSend_4.setText(_translate("MainWindow", "秒发送"))
        self.list_5.setText(_translate("MainWindow", "第"))
        self.secondSend_5.setText(_translate("MainWindow", "秒发送"))
        self.dataSend_list.setText(_translate("MainWindow", "生效并开始"))
        self.startConnect.setText(_translate("MainWindow", "开始连接"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

