
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef OBJDICT_H
#define OBJDICT_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data Master_Data;
extern UNS32 MasterCtrlSdo_N1_letter;		/* Mapped at index 0x2000, subindex 0x01 */
extern UNS32 MasterCtrlSdo_N1_data;		/* Mapped at index 0x2000, subindex 0x02 */
extern UNS16 N15_dose_speed;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS8 N15_mode;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS8 N15_sub_mode;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS16 N3_out_temp;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS16 N3_out_cond;		/* Mapped at index 0x2005, subindex 0x00*/
extern UNS16 N7_adc0;		/* Mapped at index 0x2006, subindex 0x00*/
extern UNS16 N7_adc1;		/* Mapped at index 0x2007, subindex 0x00*/
extern UNS16 N7_adc2;		/* Mapped at index 0x2008, subindex 0x00*/
extern UNS16 N7_adc3;		/* Mapped at index 0x2009, subindex 0x00*/
extern UNS8 N7_state;		/* Mapped at index 0x200A, subindex 0x00*/
extern UNS8 N7_BAT_H;		/* Mapped at index 0x200B, subindex 0x00*/
extern UNS8 N7_BAT_L;		/* Mapped at index 0x200C, subindex 0x00*/
extern UNS8 N7_CHARGE;		/* Mapped at index 0x200D, subindex 0x00*/
extern UNS16 N9_all_value;		/* Mapped at index 0x200E, subindex 0x00*/
extern UNS16 N9_speed;		/* Mapped at index 0x200F, subindex 0x00*/
extern UNS8 N9_mode;		/* Mapped at index 0x2010, subindex 0x00*/
extern UNS8 N9_sub_mode;		/* Mapped at index 0x2011, subindex 0x00*/
extern UNS8 N9_door_status;		/* Mapped at index 0x2012, subindex 0x00*/
extern UNS8 TT_TEST_tt_t1;		/* Mapped at index 0x2013, subindex 0x01 */
extern UNS8 TT_TEST_tt_t2;		/* Mapped at index 0x2013, subindex 0x02 */
extern UNS8 TT_TEST_tt_t3;		/* Mapped at index 0x2013, subindex 0x03 */
extern UNS8 TT_TEST_tt_t4;		/* Mapped at index 0x2013, subindex 0x04 */
extern UNS8 TT_TEST_tt_t5;		/* Mapped at index 0x2013, subindex 0x05 */
extern UNS8 TT_TEST_tt_t6;		/* Mapped at index 0x2013, subindex 0x06 */
extern UNS8 TT_TEST_tt_t7;		/* Mapped at index 0x2013, subindex 0x07 */
extern UNS8 TT_TEST_tt_t8;		/* Mapped at index 0x2013, subindex 0x08 */

#endif // OBJDICT_H
