
/* File generated by gen_cfile.py. Should not be modified. */

#include "ObjDict.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS32 MasterCtrlSdo_N1_letter = 0x0;		/* Mapped at index 0x2000, subindex 0x01 */
UNS32 MasterCtrlSdo_N1_data = 0x0;		/* Mapped at index 0x2000, subindex 0x02 */
UNS16 N15_dose_speed = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS8 N15_mode = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */
UNS8 N15_sub_mode = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS16 N3_out_temp = 0x0;		/* Mapped at index 0x2004, subindex 0x00 */
UNS16 N3_out_cond = 0x0;		/* Mapped at index 0x2005, subindex 0x00 */
UNS16 N7_adc0 = 0x0;		/* Mapped at index 0x2006, subindex 0x00 */
UNS16 N7_adc1 = 0x0;		/* Mapped at index 0x2007, subindex 0x00 */
UNS16 N7_adc2 = 0x0;		/* Mapped at index 0x2008, subindex 0x00 */
UNS16 N7_adc3 = 0x0;		/* Mapped at index 0x2009, subindex 0x00 */
UNS8 N7_state = 0x0;		/* Mapped at index 0x200A, subindex 0x00 */
UNS8 N7_BAT_H = 0x0;		/* Mapped at index 0x200B, subindex 0x00 */
UNS8 N7_BAT_L = 0x0;		/* Mapped at index 0x200C, subindex 0x00 */
UNS8 N7_CHARGE = 0x0;		/* Mapped at index 0x200D, subindex 0x00 */
UNS16 N9_all_value = 0x0;		/* Mapped at index 0x200E, subindex 0x00 */
UNS16 N9_speed = 0x0;		/* Mapped at index 0x200F, subindex 0x00 */
UNS8 N9_mode = 0x0;		/* Mapped at index 0x2010, subindex 0x00 */
UNS8 N9_sub_mode = 0x0;		/* Mapped at index 0x2011, subindex 0x00 */
UNS8 N9_door_status = 0x0;		/* Mapped at index 0x2012, subindex 0x00 */
UNS8 TT_TEST_tt_t1 = 0xAA;		/* Mapped at index 0x2013, subindex 0x01 */
UNS8 TT_TEST_tt_t2 = 0x0;		/* Mapped at index 0x2013, subindex 0x02 */
UNS8 TT_TEST_tt_t3 = 0x87;		/* Mapped at index 0x2013, subindex 0x03 */
UNS8 TT_TEST_tt_t4 = 0x43;		/* Mapped at index 0x2013, subindex 0x04 */
UNS8 TT_TEST_tt_t5 = 0xFF;		/* Mapped at index 0x2013, subindex 0x05 */
UNS8 TT_TEST_tt_t6 = 0x43;		/* Mapped at index 0x2013, subindex 0x06 */
UNS8 TT_TEST_tt_t7 = 0x5;		/* Mapped at index 0x2013, subindex 0x07 */
UNS8 TT_TEST_tt_t8 = 0xBF;		/* Mapped at index 0x2013, subindex 0x08 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Master_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Master_iam_a_slave = 0;

TIMER_HANDLE Master_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 Master_obj1000 = 0x0;	/* 0 */
                    subindex Master_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 Master_obj1001 = 0x0;	/* 0 */
                    subindex Master_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 Master_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t Master_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex Master_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 Master_obj1005 = 0x0;	/* 0 */
                    ODCallback_t Master_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex Master_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 Master_obj1006 = 0x0;	/* 0 */
                    ODCallback_t Master_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex Master_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1006 }
                     };

/* index 0x1007 :   Synchronous Window Length. */
                    UNS32 Master_obj1007 = 0x0;	/* 0 */
                    subindex Master_Index1007[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1007 }
                     };

/* index 0x1008 :   Manufacturer Device Name. */
                    INTEGER8 Master_obj1008[10] = "";
                    subindex Master_Index1008[] = 
                     {
                       { RO, visible_string, 10, (void*)&Master_obj1008 }
                     };

/* index 0x1009 :   Manufacturer Hardware Version. */
                    INTEGER8 Master_obj1009[10] = "";
                    subindex Master_Index1009[] = 
                     {
                       { RO, visible_string, 10, (void*)&Master_obj1009 }
                     };

/* index 0x100A :   Manufacturer Software Version. */
                    INTEGER8 Master_obj100A[10] = "";
                    subindex Master_Index100A[] = 
                     {
                       { RO, visible_string, 10, (void*)&Master_obj100A }
                     };

/* index 0x100C :   Guard Time. */
                    UNS16 Master_obj100C = 0x0;	/* 0 */
                    subindex Master_Index100C[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj100C }
                     };

/* index 0x1014 :   Emergency COB ID */
                    UNS32 Master_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 Master_highestSubIndex_obj1016 = 0;
                    UNS32 Master_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 Master_obj1017 = 0x0;	/* 0 */
                    ODCallback_t Master_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex Master_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 Master_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex Master_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 Master_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 Master_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x601;	/* 1537 */
                    UNS32 Master_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x581;	/* 1409 */
                    subindex Master_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x60F;	/* 1551 */
                    UNS32 Master_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x58F;	/* 1423 */
                    UNS8 Master_obj1280_Node_ID_of_the_SDO_Server = 0xF;	/* 15 */
                    subindex Master_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 Master_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x607;	/* 1543 */
                    UNS32 Master_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x587;	/* 1415 */
                    UNS8 Master_obj1281_Node_ID_of_the_SDO_Server = 0x7;	/* 7 */
                    subindex Master_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1281 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1281_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1281_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1281_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1282 :   Client SDO 3 Parameter. */
                    UNS8 Master_highestSubIndex_obj1282 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1282_COB_ID_Client_to_Server_Transmit_SDO = 0x603;	/* 1539 */
                    UNS32 Master_obj1282_COB_ID_Server_to_Client_Receive_SDO = 0x583;	/* 1411 */
                    UNS8 Master_obj1282_Node_ID_of_the_SDO_Server = 0x3;	/* 3 */
                    subindex Master_Index1282[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1282 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1282_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1282_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1282_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1283 :   Client SDO 4 Parameter. */
                    UNS8 Master_highestSubIndex_obj1283 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1283_COB_ID_Client_to_Server_Transmit_SDO = 0x609;	/* 1545 */
                    UNS32 Master_obj1283_COB_ID_Server_to_Client_Receive_SDO = 0x589;	/* 1417 */
                    UNS8 Master_obj1283_Node_ID_of_the_SDO_Server = 0x9;	/* 9 */
                    subindex Master_Index1283[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1283 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1283_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1283_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1283_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1284 :   Client SDO 5 Parameter. */
                    UNS8 Master_highestSubIndex_obj1284 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1284_COB_ID_Client_to_Server_Transmit_SDO = 0x60A;	/* 1546 */
                    UNS32 Master_obj1284_COB_ID_Server_to_Client_Receive_SDO = 0x58A;	/* 1418 */
                    UNS8 Master_obj1284_Node_ID_of_the_SDO_Server = 0xA;	/* 10 */
                    subindex Master_Index1284[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1284 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1284_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1284_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1284_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1285 :   Client SDO 6 Parameter. */
                    UNS8 Master_highestSubIndex_obj1285 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1285_COB_ID_Client_to_Server_Transmit_SDO = 0x605;	/* 1541 */
                    UNS32 Master_obj1285_COB_ID_Server_to_Client_Receive_SDO = 0x585;	/* 1413 */
                    UNS8 Master_obj1285_Node_ID_of_the_SDO_Server = 0x5;	/* 5 */
                    subindex Master_Index1285[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1285 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1285_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1285_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1285_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
                    UNS32 Master_obj1400_COB_ID_used_by_PDO = 0x18F;	/* 399 */
                    UNS8 Master_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1400_Event_Timer = 0x0;	/* 0 */
                    subindex Master_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1400_Event_Timer }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 Master_highestSubIndex_obj1401 = 5; /* number of subindex - 1*/
                    UNS32 Master_obj1401_COB_ID_used_by_PDO = 0x187;	/* 391 */
                    UNS8 Master_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1401_Event_Timer = 0x0;	/* 0 */
                    subindex Master_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1401_Event_Timer }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 Master_highestSubIndex_obj1402 = 5; /* number of subindex - 1*/
                    UNS32 Master_obj1402_COB_ID_used_by_PDO = 0x287;	/* 647 */
                    UNS8 Master_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1402_Event_Timer = 0x0;	/* 0 */
                    subindex Master_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1402_Event_Timer }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 Master_highestSubIndex_obj1403 = 5; /* number of subindex - 1*/
                    UNS32 Master_obj1403_COB_ID_used_by_PDO = 0x189;	/* 393 */
                    UNS8 Master_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1403_Event_Timer = 0x0;	/* 0 */
                    subindex Master_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1403_Event_Timer }
                     };

/* index 0x1404 :   Receive PDO 5 Parameter. */
                    UNS8 Master_highestSubIndex_obj1404 = 5; /* number of subindex - 1*/
                    UNS32 Master_obj1404_COB_ID_used_by_PDO = 0x80000003;	/* 2147483651 */
                    UNS8 Master_obj1404_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1404_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1404_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1404_Event_Timer = 0x0;	/* 0 */
                    subindex Master_Index1404[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1404 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1404_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1404_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1404_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1404_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1404_Event_Timer }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 Master_highestSubIndex_obj1600 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1600[] = 
                    {
                      0x0,	/* 0 */
                      0x20010010,	/* 536936464 */
                      0x20020008,	/* 537001992 */
                      0x20030008	/* 537067528 */
                    };
                    subindex Master_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[3] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 Master_highestSubIndex_obj1601 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1601[] = 
                    {
                      0x200A0008,	/* 537526280 */
                      0x200B0008,	/* 537591816 */
                      0x200C0008,	/* 537657352 */
                      0x200D0008	/* 537722888 */
                    };
                    subindex Master_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[3] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 Master_highestSubIndex_obj1602 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1602[] = 
                    {
                      0x20060010,	/* 537264144 */
                      0x20070010,	/* 537329680 */
                      0x20080010,	/* 537395216 */
                      0x20090010	/* 537460752 */
                    };
                    subindex Master_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1602[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1602[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1602[3] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 Master_highestSubIndex_obj1603 = 5; /* number of subindex - 1*/
                    UNS32 Master_obj1603[] = 
                    {
                      0x200E0010,	/* 537788432 */
                      0x200F0010,	/* 537853968 */
                      0x20100008,	/* 537919496 */
                      0x20110008,	/* 537985032 */
                      0x20120008	/* 538050568 */
                    };
                    subindex Master_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1603[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1603[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1603[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1603[4] }
                     };

/* index 0x1604 :   Receive PDO 5 Mapping. */
                    UNS8 Master_highestSubIndex_obj1604 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1604[] = 
                    {
                    };
                    subindex Master_Index1604[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1604 }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 Master_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 Master_obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 Master_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1800_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t Master_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex Master_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1800_Event_Timer }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 Master_obj1A00[] = 
                    {
                      0x20130108,	/* 538116360 */
                      0x20130208,	/* 538116616 */
                      0x20130308,	/* 538116872 */
                      0x20130408,	/* 538117128 */
                      0x20130508,	/* 538117384 */
                      0x20130608,	/* 538117640 */
                      0x20130708,	/* 538117896 */
                      0x20130808	/* 538118152 */
                    };
                    subindex Master_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[7] }
                     };

/* index 0x2000 :   Mapped variable MasterCtrlSdo */
                    UNS8 Master_highestSubIndex_obj2000 = 2; /* number of subindex - 1*/
                    subindex Master_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2000 },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterCtrlSdo_N1_letter },
                       { RW, uint32, sizeof (UNS32), (void*)&MasterCtrlSdo_N1_data }
                     };

/* index 0x2001 :   Mapped variable N15_dose_speed */
                    subindex Master_Index2001[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&N15_dose_speed }
                     };

/* index 0x2002 :   Mapped variable N15_mode */
                    subindex Master_Index2002[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&N15_mode }
                     };

/* index 0x2003 :   Mapped variable N15_sub_mode */
                    subindex Master_Index2003[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&N15_sub_mode }
                     };

/* index 0x2004 :   Mapped variable N3_out_temp */
                    subindex Master_Index2004[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&N3_out_temp }
                     };

/* index 0x2005 :   Mapped variable N3_out_cond */
                    subindex Master_Index2005[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&N3_out_cond }
                     };

/* index 0x2006 :   Mapped variable N7_adc0 */
                    subindex Master_Index2006[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&N7_adc0 }
                     };

/* index 0x2007 :   Mapped variable N7_adc1 */
                    subindex Master_Index2007[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&N7_adc1 }
                     };

/* index 0x2008 :   Mapped variable N7_adc2 */
                    subindex Master_Index2008[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&N7_adc2 }
                     };

/* index 0x2009 :   Mapped variable N7_adc3 */
                    subindex Master_Index2009[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&N7_adc3 }
                     };

/* index 0x200A :   Mapped variable N7_state */
                    subindex Master_Index200A[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&N7_state }
                     };

/* index 0x200B :   Mapped variable N7_BAT_H */
                    subindex Master_Index200B[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&N7_BAT_H }
                     };

/* index 0x200C :   Mapped variable N7_BAT_L */
                    subindex Master_Index200C[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&N7_BAT_L }
                     };

/* index 0x200D :   Mapped variable N7_CHARGE */
                    subindex Master_Index200D[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&N7_CHARGE }
                     };

/* index 0x200E :   Mapped variable N9_all_value */
                    subindex Master_Index200E[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&N9_all_value }
                     };

/* index 0x200F :   Mapped variable N9_speed */
                    subindex Master_Index200F[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&N9_speed }
                     };

/* index 0x2010 :   Mapped variable N9_mode */
                    subindex Master_Index2010[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&N9_mode }
                     };

/* index 0x2011 :   Mapped variable N9_sub_mode */
                    subindex Master_Index2011[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&N9_sub_mode }
                     };

/* index 0x2012 :   Mapped variable N9_door_status */
                    subindex Master_Index2012[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&N9_door_status }
                     };

/* index 0x2013 :   Mapped variable TT_TEST */
                    UNS8 Master_highestSubIndex_obj2013 = 8; /* number of subindex - 1*/
                    subindex Master_Index2013[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2013 },
                       { RW, uint8, sizeof (UNS8), (void*)&TT_TEST_tt_t1 },
                       { RW, uint8, sizeof (UNS8), (void*)&TT_TEST_tt_t2 },
                       { RW, uint8, sizeof (UNS8), (void*)&TT_TEST_tt_t3 },
                       { RW, uint8, sizeof (UNS8), (void*)&TT_TEST_tt_t4 },
                       { RW, uint8, sizeof (UNS8), (void*)&TT_TEST_tt_t5 },
                       { RW, uint8, sizeof (UNS8), (void*)&TT_TEST_tt_t6 },
                       { RW, uint8, sizeof (UNS8), (void*)&TT_TEST_tt_t7 },
                       { RW, uint8, sizeof (UNS8), (void*)&TT_TEST_tt_t8 }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Master_objdict[] = 
{
  { (subindex*)Master_Index1000,sizeof(Master_Index1000)/sizeof(Master_Index1000[0]), 0x1000},
  { (subindex*)Master_Index1001,sizeof(Master_Index1001)/sizeof(Master_Index1001[0]), 0x1001},
  { (subindex*)Master_Index1005,sizeof(Master_Index1005)/sizeof(Master_Index1005[0]), 0x1005},
  { (subindex*)Master_Index1006,sizeof(Master_Index1006)/sizeof(Master_Index1006[0]), 0x1006},
  { (subindex*)Master_Index1007,sizeof(Master_Index1007)/sizeof(Master_Index1007[0]), 0x1007},
  { (subindex*)Master_Index1008,sizeof(Master_Index1008)/sizeof(Master_Index1008[0]), 0x1008},
  { (subindex*)Master_Index1009,sizeof(Master_Index1009)/sizeof(Master_Index1009[0]), 0x1009},
  { (subindex*)Master_Index100A,sizeof(Master_Index100A)/sizeof(Master_Index100A[0]), 0x100A},
  { (subindex*)Master_Index100C,sizeof(Master_Index100C)/sizeof(Master_Index100C[0]), 0x100C},
  { (subindex*)Master_Index1017,sizeof(Master_Index1017)/sizeof(Master_Index1017[0]), 0x1017},
  { (subindex*)Master_Index1018,sizeof(Master_Index1018)/sizeof(Master_Index1018[0]), 0x1018},
  { (subindex*)Master_Index1200,sizeof(Master_Index1200)/sizeof(Master_Index1200[0]), 0x1200},
  { (subindex*)Master_Index1280,sizeof(Master_Index1280)/sizeof(Master_Index1280[0]), 0x1280},
  { (subindex*)Master_Index1281,sizeof(Master_Index1281)/sizeof(Master_Index1281[0]), 0x1281},
  { (subindex*)Master_Index1282,sizeof(Master_Index1282)/sizeof(Master_Index1282[0]), 0x1282},
  { (subindex*)Master_Index1283,sizeof(Master_Index1283)/sizeof(Master_Index1283[0]), 0x1283},
  { (subindex*)Master_Index1284,sizeof(Master_Index1284)/sizeof(Master_Index1284[0]), 0x1284},
  { (subindex*)Master_Index1285,sizeof(Master_Index1285)/sizeof(Master_Index1285[0]), 0x1285},
  { (subindex*)Master_Index1400,sizeof(Master_Index1400)/sizeof(Master_Index1400[0]), 0x1400},
  { (subindex*)Master_Index1401,sizeof(Master_Index1401)/sizeof(Master_Index1401[0]), 0x1401},
  { (subindex*)Master_Index1402,sizeof(Master_Index1402)/sizeof(Master_Index1402[0]), 0x1402},
  { (subindex*)Master_Index1403,sizeof(Master_Index1403)/sizeof(Master_Index1403[0]), 0x1403},
  { (subindex*)Master_Index1404,sizeof(Master_Index1404)/sizeof(Master_Index1404[0]), 0x1404},
  { (subindex*)Master_Index1600,sizeof(Master_Index1600)/sizeof(Master_Index1600[0]), 0x1600},
  { (subindex*)Master_Index1601,sizeof(Master_Index1601)/sizeof(Master_Index1601[0]), 0x1601},
  { (subindex*)Master_Index1602,sizeof(Master_Index1602)/sizeof(Master_Index1602[0]), 0x1602},
  { (subindex*)Master_Index1603,sizeof(Master_Index1603)/sizeof(Master_Index1603[0]), 0x1603},
  { (subindex*)Master_Index1604,sizeof(Master_Index1604)/sizeof(Master_Index1604[0]), 0x1604},
  { (subindex*)Master_Index1800,sizeof(Master_Index1800)/sizeof(Master_Index1800[0]), 0x1800},
  { (subindex*)Master_Index1A00,sizeof(Master_Index1A00)/sizeof(Master_Index1A00[0]), 0x1A00},
  { (subindex*)Master_Index2000,sizeof(Master_Index2000)/sizeof(Master_Index2000[0]), 0x2000},
  { (subindex*)Master_Index2001,sizeof(Master_Index2001)/sizeof(Master_Index2001[0]), 0x2001},
  { (subindex*)Master_Index2002,sizeof(Master_Index2002)/sizeof(Master_Index2002[0]), 0x2002},
  { (subindex*)Master_Index2003,sizeof(Master_Index2003)/sizeof(Master_Index2003[0]), 0x2003},
  { (subindex*)Master_Index2004,sizeof(Master_Index2004)/sizeof(Master_Index2004[0]), 0x2004},
  { (subindex*)Master_Index2005,sizeof(Master_Index2005)/sizeof(Master_Index2005[0]), 0x2005},
  { (subindex*)Master_Index2006,sizeof(Master_Index2006)/sizeof(Master_Index2006[0]), 0x2006},
  { (subindex*)Master_Index2007,sizeof(Master_Index2007)/sizeof(Master_Index2007[0]), 0x2007},
  { (subindex*)Master_Index2008,sizeof(Master_Index2008)/sizeof(Master_Index2008[0]), 0x2008},
  { (subindex*)Master_Index2009,sizeof(Master_Index2009)/sizeof(Master_Index2009[0]), 0x2009},
  { (subindex*)Master_Index200A,sizeof(Master_Index200A)/sizeof(Master_Index200A[0]), 0x200A},
  { (subindex*)Master_Index200B,sizeof(Master_Index200B)/sizeof(Master_Index200B[0]), 0x200B},
  { (subindex*)Master_Index200C,sizeof(Master_Index200C)/sizeof(Master_Index200C[0]), 0x200C},
  { (subindex*)Master_Index200D,sizeof(Master_Index200D)/sizeof(Master_Index200D[0]), 0x200D},
  { (subindex*)Master_Index200E,sizeof(Master_Index200E)/sizeof(Master_Index200E[0]), 0x200E},
  { (subindex*)Master_Index200F,sizeof(Master_Index200F)/sizeof(Master_Index200F[0]), 0x200F},
  { (subindex*)Master_Index2010,sizeof(Master_Index2010)/sizeof(Master_Index2010[0]), 0x2010},
  { (subindex*)Master_Index2011,sizeof(Master_Index2011)/sizeof(Master_Index2011[0]), 0x2011},
  { (subindex*)Master_Index2012,sizeof(Master_Index2012)/sizeof(Master_Index2012[0]), 0x2012},
  { (subindex*)Master_Index2013,sizeof(Master_Index2013)/sizeof(Master_Index2013[0]), 0x2013},
};

const indextable * Master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = Master_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = Master_Index1006_callbacks; break;
		case 0x1007: i = 4;break;
		case 0x1008: i = 5;break;
		case 0x1009: i = 6;break;
		case 0x100A: i = 7;break;
		case 0x100C: i = 8;break;
		case 0x1017: i = 9;*callbacks = Master_Index1017_callbacks; break;
		case 0x1018: i = 10;break;
		case 0x1200: i = 11;break;
		case 0x1280: i = 12;break;
		case 0x1281: i = 13;break;
		case 0x1282: i = 14;break;
		case 0x1283: i = 15;break;
		case 0x1284: i = 16;break;
		case 0x1285: i = 17;break;
		case 0x1400: i = 18;break;
		case 0x1401: i = 19;break;
		case 0x1402: i = 20;break;
		case 0x1403: i = 21;break;
		case 0x1404: i = 22;break;
		case 0x1600: i = 23;break;
		case 0x1601: i = 24;break;
		case 0x1602: i = 25;break;
		case 0x1603: i = 26;break;
		case 0x1604: i = 27;break;
		case 0x1800: i = 28;*callbacks = Master_Index1800_callbacks; break;
		case 0x1A00: i = 29;break;
		case 0x2000: i = 30;break;
		case 0x2001: i = 31;break;
		case 0x2002: i = 32;break;
		case 0x2003: i = 33;break;
		case 0x2004: i = 34;break;
		case 0x2005: i = 35;break;
		case 0x2006: i = 36;break;
		case 0x2007: i = 37;break;
		case 0x2008: i = 38;break;
		case 0x2009: i = 39;break;
		case 0x200A: i = 40;break;
		case 0x200B: i = 41;break;
		case 0x200C: i = 42;break;
		case 0x200D: i = 43;break;
		case 0x200E: i = 44;break;
		case 0x200F: i = 45;break;
		case 0x2010: i = 46;break;
		case 0x2011: i = 47;break;
		case 0x2012: i = 48;break;
		case 0x2013: i = 49;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &Master_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Master_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index Master_firstIndex = {
  11, /* SDO_SVR */
  12, /* SDO_CLT */
  18, /* PDO_RCV */
  23, /* PDO_RCV_MAP */
  28, /* PDO_TRS */
  29 /* PDO_TRS_MAP */
};

const quick_index Master_lastIndex = {
  11, /* SDO_SVR */
  17, /* SDO_CLT */
  22, /* PDO_RCV */
  27, /* PDO_RCV_MAP */
  28, /* PDO_TRS */
  29 /* PDO_TRS_MAP */
};

const UNS16 Master_ObjdictSize = sizeof(Master_objdict)/sizeof(Master_objdict[0]); 

CO_Data Master_Data = CANOPEN_NODE_DATA_INITIALIZER(Master);

