/********************************************************************************
** Form generated from reading UI file 'engineering_mode.ui'
**
** Created: Sat Nov 25 16:13:34 2017
**      by: Qt User Interface Compiler version 4.8.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ENGINEERING_MODE_H
#define UI_ENGINEERING_MODE_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QDialog>
#include <QtGui/QFrame>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>
#include <QtGui/QRadioButton>
#include <QtGui/QTabWidget>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Dialog
{
public:
    QPushButton *pushButton;
    QTabWidget *tabWidget;
    QWidget *status;
    QLabel *Ver;
    QLabel *BuildTime;
    QLabel *VerStr;
    QLabel *TimeStr;
    QPushButton *pbtn_update;
    QPushButton *pushButton_checkver;
    QLabel *BloodVStr;
    QLabel *Blood2VStr;
    QLabel *MornitorVStr;
    QLabel *HeparinVStr;
    QLabel *MasterVStr;
    QLabel *PowerVStr;
    QLabel *PowerVStr_2;
    QLabel *HeparinVStr_2;
    QLabel *Blood2VStr_2;
    QLabel *BloodVStr_2;
    QLabel *MornitorVStr_2;
    QLabel *MasterVStr_2;
    QLabel *versionStr;
    QLabel *builtimeStr;
    QWidget *params;
    QWidget *curve;
    QWidget *tab_3;
    QLabel *Target_b;
    QLabel *Target_mix;
    QLabel *CountScal;
    QLineEdit *lineEditNa;
    QLineEdit *lineEditHco3;
    QLabel *usedNa;
    QLabel *usedHco3;
    QWidget *factory;
    QPushButton *increase;
    QPushButton *decrease;
    QLabel *labelVolume;
    QLineEdit *disVolume;
    QFrame *line;
    QFrame *line_2;
    QCheckBox *autoOff;
    QCheckBox *remainingTime;
    QCheckBox *lastPrograms;
    QCheckBox *filterChange;
    QGroupBox *groupChemicalDisinfect;
    QRadioButton *radioPeraceticAcid;
    QRadioButton *radioSodiumCitrate;
    QRadioButton *radioChemical3;
    QGroupBox *groupCentralDisinfect;
    QRadioButton *radioCentralHot;
    QRadioButton *radioCentralChemical;
    QGroupBox *Prime;
    QRadioButton *PrimeAuto;
    QRadioButton *PrimeManual;
    QRadioButton *PrimeOnline;
    QPushButton *SaveBTN;
    QGroupBox *Prime_2;
    QPushButton *pushButton_2;
    QGroupBox *untilFiltergroupBox;
    QLineEdit *allEdit;
    QLabel *allTimeslabel;
    QLineEdit *usedEdit;
    QLabel *usedTimeslabel;
    QLabel *remainTimeslabel;
    QLineEdit *remainEdit;
    QLineEdit *remainEdit_2;
    QLineEdit *allEdit_2;
    QLabel *allTimeslabel_2;
    QLabel *usedTimeslabel_2;
    QLineEdit *usedEdit_2;
    QLabel *remainTimeslabel_2;
    QLabel *filter1Lable;
    QLabel *filter2Lable;
    QGroupBox *Prime_3;
    QRadioButton *HeparinYes;
    QRadioButton *HeparinNo;
    QGroupBox *ConnectPt;
    QRadioButton *OnlineGB;
    QRadioButton *GBbutton;
    QGroupBox *CureMode;
    QRadioButton *HD_DDBbut;
    QRadioButton *HD_SDPbut;
    QRadioButton *HD_SSPbut;
    QRadioButton *HDF_PREbut;
    QRadioButton *HDF_POSTbut;
    QRadioButton *HF_PREbut;
    QRadioButton *HF_POSTbut;
    QRadioButton *ISO_DDPbut;
    QRadioButton *ISO_SDPbut;
    QRadioButton *ISO_SSPbut;
    QRadioButton *PEbut;
    QGroupBox *ReturnBlood;
    QRadioButton *OnlineRB;
    QRadioButton *RBbutton;
    QGroupBox *Fluidmode;
    QRadioButton *AandB;
    QRadioButton *AandBPower;
    QRadioButton *Acetate;
    QRadioButton *Center;
    QPushButton *RestoreBTN;
    QGroupBox *ProfileMode;
    QCheckBox *Na_Profile_Box;
    QCheckBox *UF_Profile_Box;
    QCheckBox *Dia_Profile_Box;
    QCheckBox *Cond_Profile_Box;
    QCheckBox *Temp_Profile_Box;
    QCheckBox *Hco3_Profile_Box;
    QCheckBox *Hep_Profile_Box;
    QWidget *EEPROM;
    QGroupBox *groupBoxReadOut;
    QLabel *address;
    QLabel *outdata;
    QLabel *inputaddress;
    QGroupBox *groupBoxWrite;
    QLabel *address_2;
    QLabel *outdata_2;

    void setupUi(QDialog *Dialog)
    {
        if (Dialog->objectName().isEmpty())
            Dialog->setObjectName(QString::fromUtf8("Dialog"));
        Dialog->resize(1024, 768);
        pushButton = new QPushButton(Dialog);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(910, 725, 103, 40));
        tabWidget = new QTabWidget(Dialog);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(10, 10, 1001, 701));
        tabWidget->setFocusPolicy(Qt::TabFocus);
        status = new QWidget();
        status->setObjectName(QString::fromUtf8("status"));
        Ver = new QLabel(status);
        Ver->setObjectName(QString::fromUtf8("Ver"));
        Ver->setGeometry(QRect(40, 20, 71, 21));
        BuildTime = new QLabel(status);
        BuildTime->setObjectName(QString::fromUtf8("BuildTime"));
        BuildTime->setGeometry(QRect(40, 50, 71, 21));
        VerStr = new QLabel(status);
        VerStr->setObjectName(QString::fromUtf8("VerStr"));
        VerStr->setGeometry(QRect(120, 20, 231, 21));
        TimeStr = new QLabel(status);
        TimeStr->setObjectName(QString::fromUtf8("TimeStr"));
        TimeStr->setGeometry(QRect(120, 50, 231, 21));
        pbtn_update = new QPushButton(status);
        pbtn_update->setObjectName(QString::fromUtf8("pbtn_update"));
        pbtn_update->setGeometry(QRect(520, 290, 291, 31));
        pushButton_checkver = new QPushButton(status);
        pushButton_checkver->setObjectName(QString::fromUtf8("pushButton_checkver"));
        pushButton_checkver->setGeometry(QRect(120, 410, 111, 41));
        BloodVStr = new QLabel(status);
        BloodVStr->setObjectName(QString::fromUtf8("BloodVStr"));
        BloodVStr->setGeometry(QRect(40, 150, 101, 21));
        Blood2VStr = new QLabel(status);
        Blood2VStr->setObjectName(QString::fromUtf8("Blood2VStr"));
        Blood2VStr->setGeometry(QRect(40, 180, 101, 21));
        MornitorVStr = new QLabel(status);
        MornitorVStr->setObjectName(QString::fromUtf8("MornitorVStr"));
        MornitorVStr->setGeometry(QRect(40, 120, 111, 21));
        HeparinVStr = new QLabel(status);
        HeparinVStr->setObjectName(QString::fromUtf8("HeparinVStr"));
        HeparinVStr->setGeometry(QRect(40, 210, 111, 21));
        MasterVStr = new QLabel(status);
        MasterVStr->setObjectName(QString::fromUtf8("MasterVStr"));
        MasterVStr->setGeometry(QRect(40, 90, 111, 21));
        PowerVStr = new QLabel(status);
        PowerVStr->setObjectName(QString::fromUtf8("PowerVStr"));
        PowerVStr->setGeometry(QRect(40, 240, 101, 21));
        PowerVStr_2 = new QLabel(status);
        PowerVStr_2->setObjectName(QString::fromUtf8("PowerVStr_2"));
        PowerVStr_2->setGeometry(QRect(160, 240, 101, 21));
        HeparinVStr_2 = new QLabel(status);
        HeparinVStr_2->setObjectName(QString::fromUtf8("HeparinVStr_2"));
        HeparinVStr_2->setGeometry(QRect(160, 210, 111, 21));
        Blood2VStr_2 = new QLabel(status);
        Blood2VStr_2->setObjectName(QString::fromUtf8("Blood2VStr_2"));
        Blood2VStr_2->setGeometry(QRect(160, 180, 101, 21));
        BloodVStr_2 = new QLabel(status);
        BloodVStr_2->setObjectName(QString::fromUtf8("BloodVStr_2"));
        BloodVStr_2->setGeometry(QRect(160, 150, 101, 21));
        MornitorVStr_2 = new QLabel(status);
        MornitorVStr_2->setObjectName(QString::fromUtf8("MornitorVStr_2"));
        MornitorVStr_2->setGeometry(QRect(160, 120, 111, 21));
        MasterVStr_2 = new QLabel(status);
        MasterVStr_2->setObjectName(QString::fromUtf8("MasterVStr_2"));
        MasterVStr_2->setGeometry(QRect(160, 90, 111, 21));
        versionStr = new QLabel(status);
        versionStr->setObjectName(QString::fromUtf8("versionStr"));
        versionStr->setGeometry(QRect(120, 20, 221, 21));
        builtimeStr = new QLabel(status);
        builtimeStr->setObjectName(QString::fromUtf8("builtimeStr"));
        builtimeStr->setGeometry(QRect(120, 50, 221, 21));
        tabWidget->addTab(status, QString());
        params = new QWidget();
        params->setObjectName(QString::fromUtf8("params"));
        tabWidget->addTab(params, QString());
        curve = new QWidget();
        curve->setObjectName(QString::fromUtf8("curve"));
        tabWidget->addTab(curve, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        Target_b = new QLabel(tab_3);
        Target_b->setObjectName(QString::fromUtf8("Target_b"));
        Target_b->setGeometry(QRect(750, 240, 181, 21));
        Target_mix = new QLabel(tab_3);
        Target_mix->setObjectName(QString::fromUtf8("Target_mix"));
        Target_mix->setGeometry(QRect(750, 270, 181, 21));
        CountScal = new QLabel(tab_3);
        CountScal->setObjectName(QString::fromUtf8("CountScal"));
        CountScal->setGeometry(QRect(750, 300, 181, 21));
        lineEditNa = new QLineEdit(tab_3);
        lineEditNa->setObjectName(QString::fromUtf8("lineEditNa"));
        lineEditNa->setGeometry(QRect(845, 362, 100, 35));
        lineEditNa->setMouseTracking(false);
        lineEditNa->setFocusPolicy(Qt::StrongFocus);
        lineEditHco3 = new QLineEdit(tab_3);
        lineEditHco3->setObjectName(QString::fromUtf8("lineEditHco3"));
        lineEditHco3->setGeometry(QRect(845, 420, 100, 35));
        lineEditHco3->setMouseTracking(false);
        lineEditHco3->setFocusPolicy(Qt::StrongFocus);
        usedNa = new QLabel(tab_3);
        usedNa->setObjectName(QString::fromUtf8("usedNa"));
        usedNa->setGeometry(QRect(750, 370, 101, 21));
        usedHco3 = new QLabel(tab_3);
        usedHco3->setObjectName(QString::fromUtf8("usedHco3"));
        usedHco3->setGeometry(QRect(750, 430, 101, 21));
        tabWidget->addTab(tab_3, QString());
        lineEditNa->raise();
        Target_b->raise();
        Target_mix->raise();
        CountScal->raise();
        lineEditHco3->raise();
        usedNa->raise();
        usedHco3->raise();
        factory = new QWidget();
        factory->setObjectName(QString::fromUtf8("factory"));
        increase = new QPushButton(factory);
        increase->setObjectName(QString::fromUtf8("increase"));
        increase->setGeometry(QRect(10, 20, 85, 27));
        decrease = new QPushButton(factory);
        decrease->setObjectName(QString::fromUtf8("decrease"));
        decrease->setGeometry(QRect(200, 20, 85, 27));
        labelVolume = new QLabel(factory);
        labelVolume->setObjectName(QString::fromUtf8("labelVolume"));
        labelVolume->setGeometry(QRect(100, 26, 57, 15));
        disVolume = new QLineEdit(factory);
        disVolume->setObjectName(QString::fromUtf8("disVolume"));
        disVolume->setGeometry(QRect(155, 20, 40, 25));
        line = new QFrame(factory);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(0, 60, 1000, 3));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(factory);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(285, 0, 20, 60));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        autoOff = new QCheckBox(factory);
        autoOff->setObjectName(QString::fromUtf8("autoOff"));
        autoOff->setGeometry(QRect(300, 20, 171, 20));
        remainingTime = new QCheckBox(factory);
        remainingTime->setObjectName(QString::fromUtf8("remainingTime"));
        remainingTime->setGeometry(QRect(470, 20, 181, 20));
        lastPrograms = new QCheckBox(factory);
        lastPrograms->setObjectName(QString::fromUtf8("lastPrograms"));
        lastPrograms->setGeometry(QRect(650, 20, 181, 20));
        filterChange = new QCheckBox(factory);
        filterChange->setObjectName(QString::fromUtf8("filterChange"));
        filterChange->setGeometry(QRect(830, 20, 171, 20));
        groupChemicalDisinfect = new QGroupBox(factory);
        groupChemicalDisinfect->setObjectName(QString::fromUtf8("groupChemicalDisinfect"));
        groupChemicalDisinfect->setGeometry(QRect(10, 80, 450, 40));
        radioPeraceticAcid = new QRadioButton(groupChemicalDisinfect);
        radioPeraceticAcid->setObjectName(QString::fromUtf8("radioPeraceticAcid"));
        radioPeraceticAcid->setGeometry(QRect(5, 18, 161, 20));
        radioPeraceticAcid->setChecked(true);
        radioSodiumCitrate = new QRadioButton(groupChemicalDisinfect);
        radioSodiumCitrate->setObjectName(QString::fromUtf8("radioSodiumCitrate"));
        radioSodiumCitrate->setGeometry(QRect(160, 18, 131, 20));
        radioChemical3 = new QRadioButton(groupChemicalDisinfect);
        radioChemical3->setObjectName(QString::fromUtf8("radioChemical3"));
        radioChemical3->setGeometry(QRect(290, 18, 151, 20));
        groupCentralDisinfect = new QGroupBox(factory);
        groupCentralDisinfect->setObjectName(QString::fromUtf8("groupCentralDisinfect"));
        groupCentralDisinfect->setGeometry(QRect(540, 80, 441, 40));
        radioCentralHot = new QRadioButton(groupCentralDisinfect);
        radioCentralHot->setObjectName(QString::fromUtf8("radioCentralHot"));
        radioCentralHot->setGeometry(QRect(180, 10, 95, 20));
        radioCentralHot->setChecked(true);
        radioCentralChemical = new QRadioButton(groupCentralDisinfect);
        radioCentralChemical->setObjectName(QString::fromUtf8("radioCentralChemical"));
        radioCentralChemical->setGeometry(QRect(280, 10, 126, 20));
        Prime = new QGroupBox(factory);
        Prime->setObjectName(QString::fromUtf8("Prime"));
        Prime->setGeometry(QRect(10, 130, 491, 40));
        Prime->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        PrimeAuto = new QRadioButton(Prime);
        PrimeAuto->setObjectName(QString::fromUtf8("PrimeAuto"));
        PrimeAuto->setGeometry(QRect(130, 10, 96, 20));
        PrimeManual = new QRadioButton(Prime);
        PrimeManual->setObjectName(QString::fromUtf8("PrimeManual"));
        PrimeManual->setGeometry(QRect(240, 10, 96, 20));
        PrimeOnline = new QRadioButton(Prime);
        PrimeOnline->setObjectName(QString::fromUtf8("PrimeOnline"));
        PrimeOnline->setGeometry(QRect(350, 10, 96, 20));
        SaveBTN = new QPushButton(factory);
        SaveBTN->setObjectName(QString::fromUtf8("SaveBTN"));
        SaveBTN->setGeometry(QRect(540, 570, 91, 51));
        Prime_2 = new QGroupBox(factory);
        Prime_2->setObjectName(QString::fromUtf8("Prime_2"));
        Prime_2->setGeometry(QRect(10, 270, 491, 151));
        Prime_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        pushButton_2 = new QPushButton(Prime_2);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(270, 60, 101, 31));
        untilFiltergroupBox = new QGroupBox(factory);
        untilFiltergroupBox->setObjectName(QString::fromUtf8("untilFiltergroupBox"));
        untilFiltergroupBox->setGeometry(QRect(540, 140, 441, 171));
        allEdit = new QLineEdit(untilFiltergroupBox);
        allEdit->setObjectName(QString::fromUtf8("allEdit"));
        allEdit->setGeometry(QRect(100, 50, 61, 31));
        allTimeslabel = new QLabel(untilFiltergroupBox);
        allTimeslabel->setObjectName(QString::fromUtf8("allTimeslabel"));
        allTimeslabel->setGeometry(QRect(40, 50, 61, 21));
        usedEdit = new QLineEdit(untilFiltergroupBox);
        usedEdit->setObjectName(QString::fromUtf8("usedEdit"));
        usedEdit->setGeometry(QRect(100, 90, 61, 31));
        usedTimeslabel = new QLabel(untilFiltergroupBox);
        usedTimeslabel->setObjectName(QString::fromUtf8("usedTimeslabel"));
        usedTimeslabel->setGeometry(QRect(20, 90, 81, 21));
        remainTimeslabel = new QLabel(untilFiltergroupBox);
        remainTimeslabel->setObjectName(QString::fromUtf8("remainTimeslabel"));
        remainTimeslabel->setGeometry(QRect(10, 130, 91, 21));
        remainEdit = new QLineEdit(untilFiltergroupBox);
        remainEdit->setObjectName(QString::fromUtf8("remainEdit"));
        remainEdit->setGeometry(QRect(100, 130, 61, 31));
        remainEdit_2 = new QLineEdit(untilFiltergroupBox);
        remainEdit_2->setObjectName(QString::fromUtf8("remainEdit_2"));
        remainEdit_2->setGeometry(QRect(320, 130, 61, 31));
        allEdit_2 = new QLineEdit(untilFiltergroupBox);
        allEdit_2->setObjectName(QString::fromUtf8("allEdit_2"));
        allEdit_2->setGeometry(QRect(320, 50, 61, 31));
        allTimeslabel_2 = new QLabel(untilFiltergroupBox);
        allTimeslabel_2->setObjectName(QString::fromUtf8("allTimeslabel_2"));
        allTimeslabel_2->setGeometry(QRect(260, 50, 61, 21));
        usedTimeslabel_2 = new QLabel(untilFiltergroupBox);
        usedTimeslabel_2->setObjectName(QString::fromUtf8("usedTimeslabel_2"));
        usedTimeslabel_2->setGeometry(QRect(240, 90, 81, 21));
        usedEdit_2 = new QLineEdit(untilFiltergroupBox);
        usedEdit_2->setObjectName(QString::fromUtf8("usedEdit_2"));
        usedEdit_2->setGeometry(QRect(320, 90, 61, 31));
        remainTimeslabel_2 = new QLabel(untilFiltergroupBox);
        remainTimeslabel_2->setObjectName(QString::fromUtf8("remainTimeslabel_2"));
        remainTimeslabel_2->setGeometry(QRect(230, 130, 91, 21));
        filter1Lable = new QLabel(untilFiltergroupBox);
        filter1Lable->setObjectName(QString::fromUtf8("filter1Lable"));
        filter1Lable->setGeometry(QRect(100, 20, 61, 21));
        filter2Lable = new QLabel(untilFiltergroupBox);
        filter2Lable->setObjectName(QString::fromUtf8("filter2Lable"));
        filter2Lable->setGeometry(QRect(320, 20, 61, 21));
        Prime_3 = new QGroupBox(factory);
        Prime_3->setObjectName(QString::fromUtf8("Prime_3"));
        Prime_3->setGeometry(QRect(10, 220, 491, 40));
        Prime_3->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        HeparinYes = new QRadioButton(Prime_3);
        HeparinYes->setObjectName(QString::fromUtf8("HeparinYes"));
        HeparinYes->setGeometry(QRect(130, 10, 96, 20));
        HeparinNo = new QRadioButton(Prime_3);
        HeparinNo->setObjectName(QString::fromUtf8("HeparinNo"));
        HeparinNo->setGeometry(QRect(240, 10, 96, 20));
        ConnectPt = new QGroupBox(factory);
        ConnectPt->setObjectName(QString::fromUtf8("ConnectPt"));
        ConnectPt->setGeometry(QRect(10, 170, 241, 40));
        ConnectPt->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        OnlineGB = new QRadioButton(ConnectPt);
        OnlineGB->setObjectName(QString::fromUtf8("OnlineGB"));
        OnlineGB->setGeometry(QRect(10, 20, 141, 20));
        GBbutton = new QRadioButton(ConnectPt);
        GBbutton->setObjectName(QString::fromUtf8("GBbutton"));
        GBbutton->setGeometry(QRect(150, 20, 96, 20));
        CureMode = new QGroupBox(factory);
        CureMode->setObjectName(QString::fromUtf8("CureMode"));
        CureMode->setGeometry(QRect(10, 420, 491, 111));
        CureMode->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        HD_DDBbut = new QRadioButton(CureMode);
        HD_DDBbut->setObjectName(QString::fromUtf8("HD_DDBbut"));
        HD_DDBbut->setGeometry(QRect(10, 20, 96, 20));
        HD_SDPbut = new QRadioButton(CureMode);
        HD_SDPbut->setObjectName(QString::fromUtf8("HD_SDPbut"));
        HD_SDPbut->setGeometry(QRect(100, 20, 96, 20));
        HD_SSPbut = new QRadioButton(CureMode);
        HD_SSPbut->setObjectName(QString::fromUtf8("HD_SSPbut"));
        HD_SSPbut->setGeometry(QRect(190, 20, 96, 20));
        HDF_PREbut = new QRadioButton(CureMode);
        HDF_PREbut->setObjectName(QString::fromUtf8("HDF_PREbut"));
        HDF_PREbut->setGeometry(QRect(290, 20, 96, 20));
        HDF_POSTbut = new QRadioButton(CureMode);
        HDF_POSTbut->setObjectName(QString::fromUtf8("HDF_POSTbut"));
        HDF_POSTbut->setGeometry(QRect(390, 20, 101, 20));
        HF_PREbut = new QRadioButton(CureMode);
        HF_PREbut->setObjectName(QString::fromUtf8("HF_PREbut"));
        HF_PREbut->setGeometry(QRect(10, 50, 101, 20));
        HF_POSTbut = new QRadioButton(CureMode);
        HF_POSTbut->setObjectName(QString::fromUtf8("HF_POSTbut"));
        HF_POSTbut->setGeometry(QRect(100, 50, 101, 20));
        ISO_DDPbut = new QRadioButton(CureMode);
        ISO_DDPbut->setObjectName(QString::fromUtf8("ISO_DDPbut"));
        ISO_DDPbut->setGeometry(QRect(190, 50, 101, 20));
        ISO_SDPbut = new QRadioButton(CureMode);
        ISO_SDPbut->setObjectName(QString::fromUtf8("ISO_SDPbut"));
        ISO_SDPbut->setGeometry(QRect(290, 50, 101, 20));
        ISO_SSPbut = new QRadioButton(CureMode);
        ISO_SSPbut->setObjectName(QString::fromUtf8("ISO_SSPbut"));
        ISO_SSPbut->setGeometry(QRect(390, 50, 101, 20));
        PEbut = new QRadioButton(CureMode);
        PEbut->setObjectName(QString::fromUtf8("PEbut"));
        PEbut->setGeometry(QRect(10, 80, 101, 20));
        ReturnBlood = new QGroupBox(factory);
        ReturnBlood->setObjectName(QString::fromUtf8("ReturnBlood"));
        ReturnBlood->setGeometry(QRect(260, 170, 241, 40));
        ReturnBlood->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        OnlineRB = new QRadioButton(ReturnBlood);
        OnlineRB->setObjectName(QString::fromUtf8("OnlineRB"));
        OnlineRB->setGeometry(QRect(10, 20, 121, 20));
        RBbutton = new QRadioButton(ReturnBlood);
        RBbutton->setObjectName(QString::fromUtf8("RBbutton"));
        RBbutton->setGeometry(QRect(140, 20, 111, 20));
        Fluidmode = new QGroupBox(factory);
        Fluidmode->setObjectName(QString::fromUtf8("Fluidmode"));
        Fluidmode->setGeometry(QRect(10, 540, 491, 41));
        Fluidmode->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        AandB = new QRadioButton(Fluidmode);
        AandB->setObjectName(QString::fromUtf8("AandB"));
        AandB->setGeometry(QRect(20, 20, 96, 20));
        AandBPower = new QRadioButton(Fluidmode);
        AandBPower->setObjectName(QString::fromUtf8("AandBPower"));
        AandBPower->setGeometry(QRect(110, 20, 131, 20));
        Acetate = new QRadioButton(Fluidmode);
        Acetate->setObjectName(QString::fromUtf8("Acetate"));
        Acetate->setGeometry(QRect(250, 20, 96, 20));
        Center = new QRadioButton(Fluidmode);
        Center->setObjectName(QString::fromUtf8("Center"));
        Center->setGeometry(QRect(350, 20, 96, 20));
        RestoreBTN = new QPushButton(factory);
        RestoreBTN->setObjectName(QString::fromUtf8("RestoreBTN"));
        RestoreBTN->setGeometry(QRect(540, 490, 131, 41));
        ProfileMode = new QGroupBox(factory);
        ProfileMode->setObjectName(QString::fromUtf8("ProfileMode"));
        ProfileMode->setGeometry(QRect(540, 310, 441, 101));
        ProfileMode->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Na_Profile_Box = new QCheckBox(ProfileMode);
        Na_Profile_Box->setObjectName(QString::fromUtf8("Na_Profile_Box"));
        Na_Profile_Box->setGeometry(QRect(10, 30, 110, 20));
        UF_Profile_Box = new QCheckBox(ProfileMode);
        UF_Profile_Box->setObjectName(QString::fromUtf8("UF_Profile_Box"));
        UF_Profile_Box->setGeometry(QRect(120, 30, 110, 20));
        Dia_Profile_Box = new QCheckBox(ProfileMode);
        Dia_Profile_Box->setObjectName(QString::fromUtf8("Dia_Profile_Box"));
        Dia_Profile_Box->setGeometry(QRect(230, 30, 110, 20));
        Cond_Profile_Box = new QCheckBox(ProfileMode);
        Cond_Profile_Box->setObjectName(QString::fromUtf8("Cond_Profile_Box"));
        Cond_Profile_Box->setGeometry(QRect(330, 30, 110, 20));
        Temp_Profile_Box = new QCheckBox(ProfileMode);
        Temp_Profile_Box->setObjectName(QString::fromUtf8("Temp_Profile_Box"));
        Temp_Profile_Box->setGeometry(QRect(10, 70, 110, 20));
        Hco3_Profile_Box = new QCheckBox(ProfileMode);
        Hco3_Profile_Box->setObjectName(QString::fromUtf8("Hco3_Profile_Box"));
        Hco3_Profile_Box->setGeometry(QRect(120, 70, 110, 20));
        Hep_Profile_Box = new QCheckBox(ProfileMode);
        Hep_Profile_Box->setObjectName(QString::fromUtf8("Hep_Profile_Box"));
        Hep_Profile_Box->setGeometry(QRect(230, 70, 110, 20));
        tabWidget->addTab(factory, QString());
        EEPROM = new QWidget();
        EEPROM->setObjectName(QString::fromUtf8("EEPROM"));
        EEPROM->setEnabled(true);
        groupBoxReadOut = new QGroupBox(EEPROM);
        groupBoxReadOut->setObjectName(QString::fromUtf8("groupBoxReadOut"));
        groupBoxReadOut->setGeometry(QRect(500, 90, 271, 81));
        address = new QLabel(groupBoxReadOut);
        address->setObjectName(QString::fromUtf8("address"));
        address->setGeometry(QRect(20, 10, 91, 21));
        outdata = new QLabel(groupBoxReadOut);
        outdata->setObjectName(QString::fromUtf8("outdata"));
        outdata->setGeometry(QRect(170, 10, 71, 21));
        inputaddress = new QLabel(EEPROM);
        inputaddress->setObjectName(QString::fromUtf8("inputaddress"));
        inputaddress->setGeometry(QRect(298, 100, 131, 21));
        groupBoxWrite = new QGroupBox(EEPROM);
        groupBoxWrite->setObjectName(QString::fromUtf8("groupBoxWrite"));
        groupBoxWrite->setGeometry(QRect(500, 180, 271, 81));
        address_2 = new QLabel(groupBoxWrite);
        address_2->setObjectName(QString::fromUtf8("address_2"));
        address_2->setGeometry(QRect(20, 10, 91, 21));
        outdata_2 = new QLabel(groupBoxWrite);
        outdata_2->setObjectName(QString::fromUtf8("outdata_2"));
        outdata_2->setGeometry(QRect(170, 10, 71, 21));
        tabWidget->addTab(EEPROM, QString());
        QWidget::setTabOrder(tabWidget, pbtn_update);
        QWidget::setTabOrder(pbtn_update, pushButton_checkver);
        QWidget::setTabOrder(pushButton_checkver, pushButton);
        QWidget::setTabOrder(pushButton, filterChange);
        QWidget::setTabOrder(filterChange, increase);
        QWidget::setTabOrder(increase, decrease);
        QWidget::setTabOrder(decrease, disVolume);
        QWidget::setTabOrder(disVolume, autoOff);
        QWidget::setTabOrder(autoOff, remainingTime);
        QWidget::setTabOrder(remainingTime, lastPrograms);
        QWidget::setTabOrder(lastPrograms, radioChemical3);
        QWidget::setTabOrder(radioChemical3, radioPeraceticAcid);
        QWidget::setTabOrder(radioPeraceticAcid, radioSodiumCitrate);
        QWidget::setTabOrder(radioSodiumCitrate, radioCentralChemical);
        QWidget::setTabOrder(radioCentralChemical, radioCentralHot);
        QWidget::setTabOrder(radioCentralHot, lineEditNa);
        QWidget::setTabOrder(lineEditNa, lineEditHco3);
        QWidget::setTabOrder(lineEditHco3, PrimeAuto);
        QWidget::setTabOrder(PrimeAuto, PrimeManual);
        QWidget::setTabOrder(PrimeManual, SaveBTN);
        QWidget::setTabOrder(SaveBTN, pushButton_2);

        retranslateUi(Dialog);

        tabWidget->setCurrentIndex(4);


        QMetaObject::connectSlotsByName(Dialog);
    } // setupUi

    void retranslateUi(QDialog *Dialog)
    {
        Dialog->setWindowTitle(QApplication::translate("Dialog", "\345\267\245\347\250\213\346\250\241\345\274\217", 0, QApplication::UnicodeUTF8));
        pushButton->setText(QApplication::translate("Dialog", "\345\205\263\351\227\255\347\252\227\345\217\243", 0, QApplication::UnicodeUTF8));
        Ver->setText(QApplication::translate("Dialog", "Versions", 0, QApplication::UnicodeUTF8));
        BuildTime->setText(QApplication::translate("Dialog", "Build In", 0, QApplication::UnicodeUTF8));
        VerStr->setText(QString());
        TimeStr->setText(QString());
        pbtn_update->setText(QApplication::translate("Dialog", "Update System Software & Firmware", 0, QApplication::UnicodeUTF8));
        pushButton_checkver->setText(QApplication::translate("Dialog", "CheckVersion", 0, QApplication::UnicodeUTF8));
        BloodVStr->setText(QApplication::translate("Dialog", "BloodVersion", 0, QApplication::UnicodeUTF8));
        Blood2VStr->setText(QApplication::translate("Dialog", "Blood2Version", 0, QApplication::UnicodeUTF8));
        MornitorVStr->setText(QApplication::translate("Dialog", "MornitorVersion", 0, QApplication::UnicodeUTF8));
        HeparinVStr->setText(QApplication::translate("Dialog", "HeparinVersion", 0, QApplication::UnicodeUTF8));
        MasterVStr->setText(QApplication::translate("Dialog", "MasterVersion", 0, QApplication::UnicodeUTF8));
        PowerVStr->setText(QApplication::translate("Dialog", "PowerVersion", 0, QApplication::UnicodeUTF8));
        PowerVStr_2->setText(QApplication::translate("Dialog", "null", 0, QApplication::UnicodeUTF8));
        HeparinVStr_2->setText(QApplication::translate("Dialog", "null", 0, QApplication::UnicodeUTF8));
        Blood2VStr_2->setText(QApplication::translate("Dialog", "null", 0, QApplication::UnicodeUTF8));
        BloodVStr_2->setText(QApplication::translate("Dialog", "null", 0, QApplication::UnicodeUTF8));
        MornitorVStr_2->setText(QApplication::translate("Dialog", "null", 0, QApplication::UnicodeUTF8));
        MasterVStr_2->setText(QApplication::translate("Dialog", "null", 0, QApplication::UnicodeUTF8));
        versionStr->setText(QString());
        builtimeStr->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(status), QApplication::translate("Dialog", "Status and info", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(params), QApplication::translate("Dialog", "Params set", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(curve), QApplication::translate("Dialog", "Curve Set", 0, QApplication::UnicodeUTF8));
        Target_b->setText(QApplication::translate("Dialog", "BCond.", 0, QApplication::UnicodeUTF8));
        Target_mix->setText(QApplication::translate("Dialog", "MixCond.", 0, QApplication::UnicodeUTF8));
        CountScal->setText(QApplication::translate("Dialog", "scal", 0, QApplication::UnicodeUTF8));
        usedNa->setText(QApplication::translate("Dialog", "Curent      Na:", 0, QApplication::UnicodeUTF8));
        usedHco3->setText(QApplication::translate("Dialog", "Curent HCO3:", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("Dialog", "Formula", 0, QApplication::UnicodeUTF8));
        increase->setText(QApplication::translate("Dialog", "+", 0, QApplication::UnicodeUTF8));
        decrease->setText(QApplication::translate("Dialog", "-", 0, QApplication::UnicodeUTF8));
        labelVolume->setText(QApplication::translate("Dialog", "Volume :", 0, QApplication::UnicodeUTF8));
        disVolume->setText(QString());
        autoOff->setText(QApplication::translate("Dialog", "Display Auto Off Time", 0, QApplication::UnicodeUTF8));
        remainingTime->setText(QApplication::translate("Dialog", "Display Remaining Time", 0, QApplication::UnicodeUTF8));
        lastPrograms->setText(QApplication::translate("Dialog", "Display Last Programs", 0, QApplication::UnicodeUTF8));
        filterChange->setText(QApplication::translate("Dialog", "Display Filter Change", 0, QApplication::UnicodeUTF8));
        groupChemicalDisinfect->setTitle(QApplication::translate("Dialog", "Chemical Disinfect", 0, QApplication::UnicodeUTF8));
        radioPeraceticAcid->setText(QApplication::translate("Dialog", "Chymistry Peracetic ", 0, QApplication::UnicodeUTF8));
        radioSodiumCitrate->setText(QApplication::translate("Dialog", "Chymistry Citric", 0, QApplication::UnicodeUTF8));
        radioChemical3->setText(QApplication::translate("Dialog", "Chymistry Reserve3", 0, QApplication::UnicodeUTF8));
        groupCentralDisinfect->setTitle(QApplication::translate("Dialog", "Central Disinfect Mode", 0, QApplication::UnicodeUTF8));
        radioCentralHot->setText(QApplication::translate("Dialog", "Central Hot", 0, QApplication::UnicodeUTF8));
        radioCentralChemical->setText(QApplication::translate("Dialog", "Central Chemical", 0, QApplication::UnicodeUTF8));
        Prime->setTitle(QApplication::translate("Dialog", "Prime Select", 0, QApplication::UnicodeUTF8));
        PrimeAuto->setText(QApplication::translate("Dialog", "Auto", 0, QApplication::UnicodeUTF8));
        PrimeManual->setText(QApplication::translate("Dialog", "Manual", 0, QApplication::UnicodeUTF8));
        PrimeOnline->setText(QApplication::translate("Dialog", "Online", 0, QApplication::UnicodeUTF8));
        SaveBTN->setText(QApplication::translate("Dialog", "Save", 0, QApplication::UnicodeUTF8));
        Prime_2->setTitle(QApplication::translate("Dialog", "Edit Password", 0, QApplication::UnicodeUTF8));
        pushButton_2->setText(QApplication::translate("Dialog", "set password", 0, QApplication::UnicodeUTF8));
        untilFiltergroupBox->setTitle(QApplication::translate("Dialog", "Until Filter", 0, QApplication::UnicodeUTF8));
        allTimeslabel->setText(QApplication::translate("Dialog", "All Times", 0, QApplication::UnicodeUTF8));
        usedTimeslabel->setText(QApplication::translate("Dialog", "Used Times", 0, QApplication::UnicodeUTF8));
        remainTimeslabel->setText(QApplication::translate("Dialog", "Remain Times", 0, QApplication::UnicodeUTF8));
        allTimeslabel_2->setText(QApplication::translate("Dialog", "All Times", 0, QApplication::UnicodeUTF8));
        usedTimeslabel_2->setText(QApplication::translate("Dialog", "Used Times", 0, QApplication::UnicodeUTF8));
        remainTimeslabel_2->setText(QApplication::translate("Dialog", "Remain Times", 0, QApplication::UnicodeUTF8));
        filter1Lable->setText(QApplication::translate("Dialog", "Filter1", 0, QApplication::UnicodeUTF8));
        filter2Lable->setText(QApplication::translate("Dialog", "Filter2", 0, QApplication::UnicodeUTF8));
        Prime_3->setTitle(QApplication::translate("Dialog", "Heparin Select", 0, QApplication::UnicodeUTF8));
        HeparinYes->setText(QApplication::translate("Dialog", "YES", 0, QApplication::UnicodeUTF8));
        HeparinNo->setText(QApplication::translate("Dialog", "NO", 0, QApplication::UnicodeUTF8));
        ConnectPt->setTitle(QApplication::translate("Dialog", "Connect P.t", 0, QApplication::UnicodeUTF8));
        OnlineGB->setText(QApplication::translate("Dialog", "Online  Getblood", 0, QApplication::UnicodeUTF8));
        GBbutton->setText(QApplication::translate("Dialog", "Getblood", 0, QApplication::UnicodeUTF8));
        CureMode->setTitle(QApplication::translate("Dialog", "Cure mode", 0, QApplication::UnicodeUTF8));
        HD_DDBbut->setText(QApplication::translate("Dialog", "HD_DDB", 0, QApplication::UnicodeUTF8));
        HD_SDPbut->setText(QApplication::translate("Dialog", "HD_SDP", 0, QApplication::UnicodeUTF8));
        HD_SSPbut->setText(QApplication::translate("Dialog", "HD_SSP", 0, QApplication::UnicodeUTF8));
        HDF_PREbut->setText(QApplication::translate("Dialog", "HDF_PRE", 0, QApplication::UnicodeUTF8));
        HDF_POSTbut->setText(QApplication::translate("Dialog", "HDF_POST", 0, QApplication::UnicodeUTF8));
        HF_PREbut->setText(QApplication::translate("Dialog", "HF_PRE", 0, QApplication::UnicodeUTF8));
        HF_POSTbut->setText(QApplication::translate("Dialog", "HF_POST", 0, QApplication::UnicodeUTF8));
        ISO_DDPbut->setText(QApplication::translate("Dialog", "ISO_DDP", 0, QApplication::UnicodeUTF8));
        ISO_SDPbut->setText(QApplication::translate("Dialog", "ISO_SDP", 0, QApplication::UnicodeUTF8));
        ISO_SSPbut->setText(QApplication::translate("Dialog", "ISO_SSP", 0, QApplication::UnicodeUTF8));
        PEbut->setText(QApplication::translate("Dialog", "PE", 0, QApplication::UnicodeUTF8));
        ReturnBlood->setTitle(QApplication::translate("Dialog", "Return blood", 0, QApplication::UnicodeUTF8));
        OnlineRB->setText(QApplication::translate("Dialog", "Online Returnblood", 0, QApplication::UnicodeUTF8));
        RBbutton->setText(QApplication::translate("Dialog", "Returnblood", 0, QApplication::UnicodeUTF8));
        Fluidmode->setTitle(QApplication::translate("Dialog", "Fluid mode", 0, QApplication::UnicodeUTF8));
        AandB->setText(QApplication::translate("Dialog", "A_and_B", 0, QApplication::UnicodeUTF8));
        AandBPower->setText(QApplication::translate("Dialog", "A_and_BPower", 0, QApplication::UnicodeUTF8));
        Acetate->setText(QApplication::translate("Dialog", "Acetate", 0, QApplication::UnicodeUTF8));
        Center->setText(QApplication::translate("Dialog", "Center", 0, QApplication::UnicodeUTF8));
        RestoreBTN->setText(QApplication::translate("Dialog", "Restore Param", 0, QApplication::UnicodeUTF8));
        ProfileMode->setTitle(QApplication::translate("Dialog", "Profile mode", 0, QApplication::UnicodeUTF8));
        Na_Profile_Box->setText(QApplication::translate("Dialog", "Na Profile", 0, QApplication::UnicodeUTF8));
        UF_Profile_Box->setText(QApplication::translate("Dialog", "UF Profile", 0, QApplication::UnicodeUTF8));
        Dia_Profile_Box->setText(QApplication::translate("Dialog", "Dia Profile", 0, QApplication::UnicodeUTF8));
        Cond_Profile_Box->setText(QApplication::translate("Dialog", "Cond Profile", 0, QApplication::UnicodeUTF8));
        Temp_Profile_Box->setText(QApplication::translate("Dialog", "Temp Profile", 0, QApplication::UnicodeUTF8));
        Hco3_Profile_Box->setText(QApplication::translate("Dialog", "Hco3 Profile", 0, QApplication::UnicodeUTF8));
        Hep_Profile_Box->setText(QApplication::translate("Dialog", "Hep Profile", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(factory), QApplication::translate("Dialog", "Factory Set", 0, QApplication::UnicodeUTF8));
        groupBoxReadOut->setTitle(QApplication::translate("Dialog", "ReadOut", 0, QApplication::UnicodeUTF8));
        address->setText(QApplication::translate("Dialog", "Address(dec)", 0, QApplication::UnicodeUTF8));
        outdata->setText(QApplication::translate("Dialog", "data(dec)", 0, QApplication::UnicodeUTF8));
        inputaddress->setText(QApplication::translate("Dialog", "Input Address(dec)", 0, QApplication::UnicodeUTF8));
        groupBoxWrite->setTitle(QApplication::translate("Dialog", "Input", 0, QApplication::UnicodeUTF8));
        address_2->setText(QApplication::translate("Dialog", "Address(dec)", 0, QApplication::UnicodeUTF8));
        outdata_2->setText(QApplication::translate("Dialog", "data(dec)", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(EEPROM), QApplication::translate("Dialog", "EEPROM", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class Dialog: public Ui_Dialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ENGINEERING_MODE_H
